services:
  postgres:
    image: postgres:16
    container_name: velib_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_sql:/docker-entrypoint-initdb.d

  api:
    build: .
    container_name: velib_api
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres

volumes:
  postgres_data:
