services:
  postgres:
    image: postgres:16
    container_name: velib_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_sql:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
